### ISSUE TITLE
Apresetar tarefas com prioridade alta em negrito

### ISSUE THREAD

**Issue by f-mattioli** [f-mattioli/lista-tarefas#10]
RQ 3: Tarefas com prioridade alta devem ser apresentadas em negrito.

**Comment by mihcaelmsn2008** [comment]
Tarefa em desenvolvimento por Michael Xavier e João Pedro

**Comment by luan1992** [comment]
em revisão por luan

**Comment by luan1992** [comment]
revisão ok
