### ISSUE TITLE
Acrescentar cabeçalho na lista de tarefas

### ISSUE THREAD

**Issue by f-mattioli** [f-mattioli/lista-tarefas#13]
Sugestão de labels: Tarefa, Prioridade, Data limite e Concluída.

**Comment by ghost** [comment]
Tarefa em Desenvolvimento por João I. Cardoso

**Comment by jpss-carvalho** [comment]
Revisando por João Pedro

**Comment by jpss-carvalho** [comment]
Revisão OK

**Comment by f-mattioli** [comment]
Demanda concluída no PR 17.
